MicrosoftLearning/AZ-500-Azure-Security

Instructions/Labs/Module_3/LAB_01_Azure Monitor.md

Current javascript generates 404 and prevents from finishing the lab as no data is pushed to Application Insights.
The javascript I've put in place works for me and enabled me to finish the lab successfully.
Fixes # .
-
-
-

Update LAB_01_Azure Monitor.md

---

Instructions/Labs/Module_2/LAB_10_Load Balancer and App Gateway.md

updated file to load missing screenshot
Fixes # .
updated file to load missing screenshot

Update LAB_10_Load Balancer and App Gateway.md

---

Instructions/Labs/Module_1/LAB_01_PIM.md
Instructions/Labs/Module_4/LAB_01_Classify a SQL Database.md

Fixes # .
Minor wording changes to Mod 4 Lab 1 exercise 1 for SQL Advanced Data security.

minor wording changes to Mod 4 Lb1 ex 1.

---

Instructions/Labs/Module_3/LAB_01_Classify a SQL Database.md
Instructions/Labs/Module_3/LAB_02_Auditing a Database.md
Instructions/Labs/Module_3/LAB_03_Analyze audit logs and reports.md

minor ammendments

---

Instructions/Labs/Module_1/LAB_01_PIM.md

Grammar fixes and a few interface updates
Fixes # .
-
-
-

Updates to LAB_01_PIM.md

---

Instructions/Labs/Module_1/LAB_02_Set up Always Encrypted (Key Vault).md

Lots of grammatical fixes and a few interface updates.  In particular, updated instructions for Application Registration
-
-
-

Update LAB_02_Set up Always Encrypted (Key Vault).md

---

Instructions/Labs/Module_1/LAB_09_Subscriptions.md

Grammar and punctuation fixes

---

Instructions/Labs/Module_1/LAB_05_Application_Service_Principal.md

Small grammar and punctuation fixes

---

Instructions/Labs/Module_3/LAB_03_Analyze audit logs and reports.md

Changes to module/lab numbers
Fixes # .
-
-
-

Update LAB_03_Analyze audit logs and reports.md

---

Instructions/Labs/Module_2/LAB_02_Function Apps.md

Update LAB_02_Function Apps.md

---

Instructions/Labs/Module_2/LAB_01_Monitor & Autoscale.md

Fixes # .
- Changed template setup to directly take you to the Azure portal.
- I've made this change as `start $url` doesn't work in AZ powershell, or is ambiguous

Fix deployment issue with Module 2/Lab 1

---

Instructions/Labs/Module_1/LAB_03_MFA.md

Removed section from code block to properly format list
Fixes # .
- Removed indentation to properly format list
-
-

Fixed formatting

---

Instructions/Labs/Module_1/LAB_02_Key_Vault.md

Fixes # .
Updated PowerShell cmdlets from AzureRM to AZ

Replaced AzureRM with AZ in PowerShell

---

Instructions/Labs/Module_2/LAB_01_Monitor & Autoscale.md

Select custom autoscale instead of Enable autoscale.
Fixes # .
Select Custom Autoscale instead of Enable Autoscale.
-
-
-

Custom autoscale

---

Instructions/Labs/Module_2/LAB_01_Monitor & Autoscale.md

Update LAB_01_Monitor & Autoscale.md

---

Instructions/Labs/Module_1/LAB_01_PIM.md
Instructions/Labs/Module_1/LAB_02_Key_Vault.md

The md files didn't compile to pdf. I removed some invalid characters.

Removed some invalid characters that prevent compilation to pdf

---

Instructions/Labs/Module_1/LAB_02_Key_Vault.md

Changed Mod 1 Ex 2 Tsk 10 to .NET Framework 4.7.2.
-
-

Changed Mod 1 Ex 2 Tsk 10 to .NET Framework 4.7.2.

---

Instructions/Labs/Module_3/LAB_01_Classify a SQL Database.md

by instead of vy
Data Discovery and Classication is not in preview anymore
Fixes # .
by instead of vy
Data Discovery & Classication is not in preview anymore (card)
-
-
-

Mod 3 Lab 1 small UI updates

---

Instructions/Labs/Module_2/LAB_17_Update Management.md

Updated information
Fixes # .
- Spelling/typos
- Updated information
-

Update LAB_17_Update Management.md

---

Instructions/Labs/Module_2/LAB_12_Azure Firewall.md

Updated instructions - Must select the NIC first i.e `srv-work267`
Updated formatting
Fixes # .
- Updated instructions
- Formatting
-

Update LAB_12_Azure Firewall.md

---

Instructions/Labs/Module_2/LAB_11_VPN Gateways and Tunnelling.md

Fixed screenshot
Fixes # .
-
-
-

Update LAB_11_VPN Gateways and Tunnelling.md

---

Instructions/Labs/Module_3/LAB_01_Classify a SQL Database.md

updated information
formatting
Fixes # .
- information
- formatting
-

Update LAB_01_Classify a SQL Database.md

---

Instructions/Labs/Module_3/LAB_02_Auditing a Database.md

Update LAB_02_Auditing a Database.md

---

Instructions/Labs/Module_2/LAB_19_Private DNS.md

Formatting
Fixes # .
- Formatting
-
-

Update LAB_19_Private DNS.md

---

Instructions/Labs/Module_4/LAB_02_Security Center.md

Fixed some typing errors
Fixes # .
-
-
-

Update LAB_02_Security Center.md

---

Allfiles/Labs/Mod1_Lab02/program.cs

Added missing }
in allfiles/Labs/Mod1_Lab02/program.cs

added missing }

---

Instructions/Labs/Module_1/LAB_02_Key_Vault.md

+ Fixed 3 typos/grammar errors
+ Changed the order of events to reflect the actual process (enter password, then data is populated in the table)
Fixes # .
- 3 typos/grammar errors
- Changing the phrasing related to the console app process
-

Updates to LAB_02_Key_Vault.md

---

Instructions/Labs/Module_2/LAB_03_Create a Kubernetes Cluster.md

Fixes # .
- A few grammar/spelling fixes
- View Container Logs requires a Log Analytics workspace, which isn't set up for this lab. The option "View live data (preview)" displays stderr and stdin without the need to set up a Log Analytics workspace

Update LAB_03_Create a Kubernetes Cluster.md

---

Instructions/Labs/Module_2/LAB_04_Create a VNet.md

Fixes # .
-"None" is no longer the default for Public Inbound Ports
- Public IP should be (new) myVm1-ip instead of (new) myVm-ip
- The "Connect" to VM interface has changed
- There's no need to minimize the remote desktop at the end of Task 4 because Task 5 begins within the remote desktop
- Removed a couple of extra commas

Update LAB_04_Create a VNet.md

---

Instructions/Labs/Module_2/LAB_07_Service Endpoints.md

Fixes # .
- Cleaned up some commas and a couple of small interface changes.
- The graphic that is displayed when access to the file share is denied has changed slightly. I've attached a sample
-
-

Update LAB_07_Service Endpoints.md

---

Instructions/Labs/Module_4/LAB_08_Create security baselines.md

Fix typo
Fixes # .
- Fix typo
-
-

Update LAB_08_Create security baselines.md

---

Instructions/Labs/Module_4/LAB_06_Security Playbook in Azure Sentinel.md

There was an incomplete sentence on Exercise 1, Task 1, Step 6
Clarified some steps
Fixes # .
-
-
-

Clarifications

---

Instructions/Labs/Module_1/LAB_02_Key_Vault.md

Fixes # 116
Changes proposed in this pull request: Fixes issue that causes sql query to render incorrectly
-
-
-

Fix Syntax Error

---

Instructions/Labs/Module_1/LAB_06_RBAC.md

Fixes # .
Changes proposed in this pull request: Changed spacing to 4 spaces following GitHub Markdown guidelines
-
-
-

Fixed Formatting Error Incorrect Spacing

---

Instructions/Labs/Module_2/LAB_02_Function Apps.md
Instructions/Labs/Module_2/LAB_03_Create a Kubernetes Cluster.md
Instructions/Labs/Module_2/LAB_07_Service Endpoints.md
Instructions/Labs/Module_2/LAB_10_Load Balancer and App Gateway.md
Instructions/Labs/Module_2/LAB_11_VPN Gateways and Tunnelling.md
Instructions/Labs/Module_2/LAB_12_Azure Firewall.md
Instructions/Labs/Module_2/LAB_13_Secure Admin Access.md
Instructions/Labs/Module_2/LAB_14_Azure Bastion.md
Instructions/Labs/Module_2/LAB_19_Private DNS.md
Instructions/Labs/Module_2/LAB_20_Azure Blueprints.md
Instructions/Labs/Module_3/LAB_01_Classify a SQL Database.md
Instructions/Labs/Module_3/LAB_02_Auditing a Database.md
Instructions/Labs/Module_3/LAB_03_Analyze audit logs and reports.md

Fixes # .
Changes proposed in this pull request: Fixes spacing issues in all modules should render agnostically at this point
-
-
-

Redo all spacing on code blocks

---

Instructions/Labs/Module_2/LAB_02_Function Apps.md

funtion to function
Fixes # .
-
-
-

Typo in Task 3 > Step 3

---

Instructions/Labs/Module_1/LAB_02_Key_Vault.md

Fixes # .
Replaced non breaking space in script that was leading to rendering errors
-
-
-

Fixed Space Encoding
